---
- name: Deploy nftables ruleset
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0644"
    validate: "nft -c -f %s"
  notify: Reload nftables

- name: Enable nftables
  ansible.builtin.service:
    name: nftables
    enabled: true
    state: started
